language: cpp
sudo: false

os:
#- linux
- osx

osx_image: xcode7.1

compiler:
#- gcc
- clang

env:
- BUILD_TYPE=Debug
#- BUILD_TYPE=Release

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

#- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
#- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/versions; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CXX" = "g++" ]; then brew install gcc49 || brew link --overwrite gcc49; fi
#- if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CXX" = "clang++" ]; then brew install llvm36 --with-clang || brew link --overwrite llvm36; fi

script:
- mkdir -p build
- cd build
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
- make
- ./test-harness

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++-4.9-dev
    - llvm-3.6
    - llvm-3.6-dev
    - clang-3.6
    - g++-4.9
