containers:
  build:
    setup:
    - !UbuntuRelease { version: 14.04 }
    - !UbuntuUniverse
    - !Install [ software-properties-common, wget, make, cmake, clang, gcc, g++, libboost-all-dev, ca-certificates, gdbserver ]
    - !Sh |
        add-apt-repository ppa:ubuntu-toolchain-r/test -y
        wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -
        add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main' -y
        apt-get update -qq
        apt-get install -y libboost-all-dev
        apt-get install -qq libstdc++-4.9-dev llvm-3.6 llvm-3.6-dev clang-3.6; fi
    volumes:
      /tmp: !Tmpfs {size: 1Gi}

commands:
  build: !Command
    description: Build C++
    accepts-arguments: false
    container: build
    work-dir: .
    run: |
      mkdir -p build/gcc
      cd build/gcc
      cmake ../..
      make -j 8
  build-clang: !Command
    description: Build C++ with clang
    accepts-arguments: false
    container: build
    work-dir: .
    environ: { CXX: clang++-3.6, CC: clang-3.6 }
    run: |
      mkdir -p build/clang
      cd build/clang
      cmake -DCMAKE_BUILD_TYPE=Release ../..
      make -j 8
  test: !Command
    description: Run tests
    accepts-arguments: true
    container: build
    work-dir: .
    run: |
      build/gcc/test-harness "$@"
  test-clang: !Command
    description: Run tests built with clang
    accepts-arguments: true
    container: build
    work-dir: .
    run: |
      build/clang/test-harness "$@"
